dome9_cloud_security_group.external_id fix
dome9/terraform-provider-dome9 pull request #133
Opened 2022-03-02 12:01 UTC by DanielRis

`data.dome9_cloud_security_group.external_id` should contain the AWS Security Group ID, not the VPC id.

2022-03-22 09:32 UTC, dolevh-d9 approved these changes

2022-03-22 09:34 UTC, dolevh-d9 requested changes
It will be merged after the test will pass

2022-03-24 08:16 UTC, DanielRis commented
> It will be merged after the test will pass
Is this something you will fix? The test fails because it complains about not having Dome9 credentials to run all the test.

2022-03-28 07:32 UTC, dolevh-d9 commented
> > It will be merged after the test will pass
> 
> Is this something you will fix @dolevh-d9? The test fails because it complains about not having Dome9 credentials to run all the test.

Yep

2022-05-02 10:49 UTC, dolevh-d9 approved these changes

2022-05-02 10:51 UTC, merged

2022-05-02 10:51 UTC, dolevh-d9 commented
@DanielRis - Mereged
THX