AL-2741 Add retry for AWP tests
dome9/terraform-provider-dome9 pull request #216
Opened 2024-08-05 20:35 UTC by batyakopelowitz

2024-08-07 06:06 UTC, dolevh-d9 commented on vendor/github.com/dome9/dome9-sdk-go/services/awp/onboarding_common.go
> +		return client.NewRequestDo("POST", path, queryParams, req, nil)
pls use NewRequestDoRetry func.
example:
![image](https://github.com/user-attachments/assets/a2d1c63a-b3c2-4ea6-ab9f-aeef74c6a6ea)

2024-08-07 06:06 UTC, dolevh-d9 requested changes
note the note

2024-08-07 11:05 UTC, batyakopelowitz commented on vendor/github.com/dome9/dome9-sdk-go/services/awp/onboarding_common.go
> +		return client.NewRequestDo("POST", path, queryParams, req, nil)
done

2024-08-08 06:11 UTC, shayde78 approved these changes
LGTM

2024-08-08 07:34 UTC, dolevh-d9 approved these changes

2024-08-08 07:34 UTC, merged